"""add case_file metadata fields

Revision ID: a03f5cdfa397
Revises: 5d5e2b6f12ec
Create Date: 2025-11-24 00:24:43.596754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03f5cdfa397'
down_revision: Union[str, Sequence[str], None] = '5d5e2b6f12ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
